name: Build and deploy ASP.Net Core app to Azure Web App - PesqueiroCarpa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build PesqueiroNetApi.csproj --configuration Release
        working-directory: PesqueiroNetApi_SQLServer/PesqueiroNetApi_SQLServer

      - name: dotnet publish
        run: dotnet publish PesqueiroNetApi.csproj -c Release -o ./myapp
        working-directory: PesqueiroNetApi_SQLServer/PesqueiroNetApi_SQLServer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PesqueiroCarpa'
          slot-name: 'Production'
          package: ./myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D230D0B934CA492E924FC686EF335914 }}
